# =================================================================
# 1. SERVER CONFIGURATION
# =================================================================
server.port=8385
# 8081 of the prod settings may be taken by another application started locally
management.server.port=8386

spring.rabbitmq.host=${MQ_HOST:localhost}
spring.rabbitmq.port=${MQ_PORT:5672}

spring.rabbitmq.username=${MQ_USERNAME:guest}
spring.rabbitmq.password=${MQ_PASSWORD:guest}
